#!/bin/bash
#
# Run the initdb, then start solr in the foreground
set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
    fi

. /opt/hbp-lucene-solr-docker/scripts/run-initdb

echo "Starting HBP Spatial Search API (using Solr-$SOLR_VERSION)"

exec solr -f "$@"
